language: python

python:
  - 3.6

install:
  - pip install Cython==0.27.3
  - pip install -r requirements_dev.txt

script:
  - flake8 aioapp examples tests setup.py
  - bandit -r ./aioapp ./examples setup.py
  - mypy aioapp examples setup.py --ignore-missing-imports
  - pytest -v

deploy:
  provider: pypi
  user: inplat
  distributions: sdist bdist_wheel
  password:
    secure: LNDVL/i6jbg3NkB3NJDk5n84prKliRbzuu4J3e889GHV7vY4B23UpUDP/R5gca2OdGqpJZBDBBO2G6Fjtmts1Jl7BytoI9cWRGtxrycBfcr93XlRu2reIqmd1ntHogv3J/TvpyzcI26xqan3XydOJ1UtxJkqpXumW2Rcdi5honaMstm9ZrpTFS8Bp42PHEymhv6AHHDEB/sPCIS3ZnCAxWl2Ova6bs8AOYjPpRzX7gUIQZvSy1quxVIgLv61hQleUv9O2G6XLYijf31YKZQvpUzUktkAGbazsjtsJmQT5l2ZSS4kq6s+QI5xjlRBe+UvIoKwNn9d24yMK5FQKTRv+xBft9dBEkYPUdwvac89hLWEMWFDdMdsmaRWz2iO3uIvnLe3OI0pCraSazymEba48N9DYZ0VuWZLS7/9SmeY/oBJBHRPOn2w1MPLuE9U1YjknGWz6PnxLlvWI09W61YPDzcy5V8WG28MTJPPqMRSejhB139V4ddTRm927L6VM6H87GJWY8QPT09flVuJzPuDnxtjhMOW4g2hHFw+ZiHDafVQcAVdkVsSDvDNjXFF1pyfdIEWU3MVa8oUIKX2oi3jmvHaaeJgqmaEt8g3j8zK1eDmD5/D+617WVxFPdCdxvOlU+x/wP9mfAhVifHU3xEHvqM/2SV5UPiKgCjJwCd/GlY=
  on:
    tags: true
