version: '2'
services:
  tracer:
    image: jaegertracing/all-in-one
    ports:
      - "9411:9411"
      - "16686:16686"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    logging:
      driver: none
  postgres:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=db
